# Generated by Django 4.1 on 2022-08-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="post_code",
            new_name="postal_code",
        ),
        migrations.AddField(
            model_name="order",
            name="country_code",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_option",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="address1",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="order",
            name="address2",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_paid",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
